"""Add CssClassName to SupplyStatuses table

Revision ID: c7caa6fe9a2f
Revises: 37e1e620171c
Create Date: 2025-05-20 19:28:16.327114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c7caa6fe9a2f'
down_revision = '37e1e620171c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('OrderItems', schema='StockWeavix') as batch_op:
        batch_op.create_foreign_key(None, 'Orders', ['OrderID'], ['OrderID'], referent_schema='StockWeavix')

    with op.batch_alter_table('SupplyStatuses', schema='StockWeavix') as batch_op:
        batch_op.add_column(sa.Column('CssClassName', sa.String(length=50), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SupplyStatuses', schema='StockWeavix') as batch_op:
        batch_op.drop_column('CssClassName')

    with op.batch_alter_table('OrderItems', schema='StockWeavix') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B612184EB88')
    )
    # ### end Alembic commands ###
